# Play for add clients and interconnect repos on RHEL 7.
---
- name: Add interconnect repo on rhel7 VM.
  #hosts: rhel7
  shell: subscription-manager repos --enable=amq-interconnect-1-for-rhel-7-server-rpms

- name: Add client repo on rhel7 VM..
  shell: subscription-manager repos --enable=a-mq-clients-1-for-rhel-7-server-beta-rpms
